### ISSUE TITLE
Android'te veri saklamak için kaç yol vardır ?

### ISSUE THREAD

**Issue by durannumit** [yusufcakmak/Android-Mulakat#1]

**Comment by yusufcakmak** [comment]
5 yol vardır. Shared preferences, Internal Storage, Local cache, External Storage, SQLite Database, Content Provider, Network Connection.

**Comment by mustafaberkaymutlu** [comment]
Burada 7 tane yöntem var. Bir de Content Provider ile veri saklanamıyor:
"A content provider is an optional component that exposes read/write access to your application data"
https://developer.android.com/guide/topics/data/data-storage.html
