### ISSUE TITLE
Java 9 ile gelen özellikler nelerdir?

### ISSUE THREAD

**Issue by sbozturk** [yusufcakmak/Android-Mulakat#5]
Tüm özellikler:
http://openjdk.java.net/projects/jdk9/

Başlıca özellikler:
http://www.baeldung.com/new-java-9

**Comment by muratcanbur** [comment]
Buradan sektöre sesleniyorum, bunu lütfen mülakatlarda sormayın :P

**Comment by yusufcakmak** [comment]
ahahah @muratcanbur sesini buradan duyuramazsın gibi 😄
